# .github/workflows/sync.yml
name: Delete Directory

on:
  push:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set variables
      run: |
        USER="${{ github.actor }}"
        REPO="${{ github.event.repository.name }}"
        DIR="${USER}@${REPO}"
        echo "USER=$USER" >> $GITHUB_ENV
        echo "REPO=$REPO" >> $GITHUB_ENV
        echo "DIR=$DIR" >> $GITHUB_ENV

    - name: Clone target repo and remove directory
      run: |
        git clone https://${{ secrets.GH_SYNC_TOKEN }}@github.com/ssm123ssm/preview.git
        rm -rf preview/public/protected/$DIR
        cd preview
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Remove directory from shared repo"
          git push
        else
          echo "No changes to commit"
        fi
